title: Jun Zhang's Homepage
page-top-title: Jun Zhang
top-section-bg-text: Electrical Engineering
home-subtitle: Jun Zhang&ensp;|&ensp;张钧
copyright-text: '&copy; Jun Zhang 2024-2025. All Rights Reserved.'
